default: &default
  adapter: postgresql
  encoding: utf8
  host: 127.0.0.1
  pool: 5

development:
  <<: *default
  database: entity_trigger_development_raj
  username: mvp
  password: secret

test:
  <<: *default
  database: entity_trigger_test
  username: mvp
  password: secret
